replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/terraform-project-382315/artemis/artemis
  tag: "10.0.0"

service:
  port: 5000

ingress:
  enabled: true
  className: "nginx"
  annotations: 
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
  hosts:
    - host: artemis-dev.projectxconsulting.net
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
   - secretName: artemis-dev-tls
     hosts:
       - artemis-dev.projectxconsulting.net
       