apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-dev
  namespace: nginx-dev
spec:
  project: default

  source:
    repoURL: https://github.com/farrukh90/probable-doodle.git
    path: application
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../envs/dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-dev

  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
